### ISSUE TITLE
Nightly builds do not seem to be running

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-nightly#5]
Should we have more than one nightly build by now?

**Comment by karianna** [comment]
There seems to be a duplicate u152 build in the releases section now and no u151?

**Comment by gdams** [comment]
they are the nightly builds, the build the latest tag from master

**Comment by karianna** [comment]
Oh I see, sorry, I didn't see the separate dates there.  So this can be closed now?

**Comment by gdams** [comment]
fixed
