### ISSUE TITLE
Hashes do not match the built files

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/openjdk-nightly#8]
https://github.com/AdoptOpenJDK/openjdk-nightly/releases/download/jdk8u152-b04-20172605/OpenJDK8_x64_Linux_20172605.sha256.txt

Is a file containing:
```
ae654c65d76e4801feea94cbb6cc33f5a7d6bc34ff8d773aed585036dec0de40  OpenJDK8_x64_Linux_201726051600.tar.gz
```

i.e its a hash for a file called `OpenJDK8_x64_Linux_201726051600.tar.gz` but the file available for download is called `OpenJDK8_x64_Linux_20172605.tar.gz`

**Comment by gdams** [comment]
@johnoliver very good spot, I forgot that we renamed the tarball after generating the checksum, I assume the hash is still correct? I'll look at tweaking the job to account for this

**Comment by gdams** [comment]
fix needs to be applied here https://github.com/AdoptOpenJDK/openjdk-website-backend/blob/master/sbin/Release.sh#L54-L79

**Comment by johnoliver** [comment]
Yeah the hash is correct, just the wrong name

**Comment by gdams** [comment]
Okay so we just need to find a way to update the file name in the checksum

**Comment by gdams** [comment]
okay resoved now
